# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nntrain',
                'doc_host': 'https://lucasvw.github.io',
                'git_url': 'https://github.com/lucasvw/nntrain',
                'lib_path': 'nntrain'},
  'syms': {'nntrain.core': {'nntrain.core.foo': ('core.html#foo', 'nntrain/core.py')}}}
