# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nntrain',
                'doc_host': 'https://lucasvw.github.io',
                'git_url': 'https://github.com/lucasvw/nntrain',
                'lib_path': 'nntrain'},
  'syms': { 'nntrain.core': {'nntrain.core.foo': ('core.html#foo', 'nntrain/core.py')},
            'nntrain.dataloaders': { 'nntrain.dataloaders.DataLoaders': ('dataloaders.html#dataloaders', 'nntrain/dataloaders.py'),
                                     'nntrain.dataloaders.DataLoaders.__init__': ( 'dataloaders.html#dataloaders.__init__',
                                                                                   'nntrain/dataloaders.py'),
                                     'nntrain.dataloaders.DataLoaders._get_dls': ( 'dataloaders.html#dataloaders._get_dls',
                                                                                   'nntrain/dataloaders.py'),
                                     'nntrain.dataloaders.DataLoaders.from_hf_dd': ( 'dataloaders.html#dataloaders.from_hf_dd',
                                                                                     'nntrain/dataloaders.py'),
                                     'nntrain.dataloaders.hf_ds_collate_func': ( 'dataloaders.html#hf_ds_collate_func',
                                                                                 'nntrain/dataloaders.py'),
                                     'nntrain.dataloaders.print_hello': ('dataloaders.html#print_hello', 'nntrain/dataloaders.py')}}}
